"""
LivePortrait local inference — generates a loopable talking animation from a static headshot.

First run: clones the LivePortrait repo to models/liveportrait/ and installs its dependencies.
Subsequent runs: skips setup and goes straight to inference.

CPU is supported but slow (~5-20 min per image). Use the Colab notebook for GPU speed.

No template video required — uses LivePortrait's built-in talking.pkl by default.
"""

import os
import sys
import glob
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
MODELS_DIR = PROJECT_ROOT / "models"
REPO_DIR = MODELS_DIR / "liveportrait"
SETUP_FLAG = REPO_DIR / ".setup_done"
WEIGHTS_FLAG = REPO_DIR / ".weights_done"

# Hybrid template: talking.pkl head/shoulder motion (10× rotation vs d5) + d8.pkl expression variety
# Generated by scripts/m1/liveportrait.py patch step; not present in the original repo clone.
_DEFAULT_DRIVING = str(REPO_DIR / "assets" / "examples" / "driving" / "talking_with_movement.pkl")
# Fallback if hybrid isn't generated yet (first-run or fresh clone)
_FALLBACK_DRIVING = str(REPO_DIR / "assets" / "examples" / "driving" / "d8.pkl")

# KwaiVGI org was renamed to KlingTeam on HuggingFace.
# HF repo paths (no "pretrained_weights/" prefix) map to local pretrained_weights/ subdir.
_WEIGHT_FILES = [
    "liveportrait/base_models/appearance_feature_extractor.pth",
    "liveportrait/base_models/motion_extractor.pth",
    "liveportrait/base_models/spade_generator.pth",
    "liveportrait/base_models/warping_module.pth",
    "liveportrait/retargeting_models/stitching_retargeting_module.pth",
    "liveportrait/landmark.onnx",
]
_HF_REPO_ID = "KlingTeam/LivePortrait"
# local_dir for hf_hub_download — files land at local_dir/<hf_path>
_WEIGHTS_LOCAL_DIR = REPO_DIR / "pretrained_weights"


def _setup() -> None:
    if SETUP_FLAG.exists():
        return
    MODELS_DIR.mkdir(exist_ok=True)
    if not REPO_DIR.exists():
        print("[LivePortrait] Cloning repo (one-time setup)...")
        subprocess.run(
            ["git", "clone", "https://github.com/KwaiVGI/LivePortrait", str(REPO_DIR)],
            check=True,
        )

    # Step 1: PyTorch CPU (not listed in LivePortrait's requirements — assumed pre-installed).
    print("[LivePortrait] Installing PyTorch (CPU)...")
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "torch", "torchvision", "torchaudio",
         "--index-url", "https://download.pytorch.org/whl/cpu"],
        check=True,
    )

    # Step 2: Base requirements (excludes onnxruntime-gpu which needs CUDA).
    print("[LivePortrait] Installing base requirements...")
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-r", str(REPO_DIR / "requirements_base.txt")],
        check=True,
    )

    # Step 3: CPU onnxruntime + remaining deps (replaces onnxruntime-gpu).
    print("[LivePortrait] Installing onnxruntime (CPU) + transformers...")
    subprocess.run(
        [sys.executable, "-m", "pip", "install",
         "onnxruntime", "transformers==4.38.0", "huggingface_hub"],
        check=True,
    )

    SETUP_FLAG.touch()
    print("[LivePortrait] Setup complete.")


def _download_weights() -> None:
    """Download LivePortrait model weights from HuggingFace (one-time, ~600 MB)."""
    if WEIGHTS_FLAG.exists():
        return
    print("[LivePortrait] Downloading model weights from HuggingFace KwaiVGI/LivePortrait...")
    try:
        from huggingface_hub import hf_hub_download
    except ImportError:
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "huggingface_hub"],
            check=True,
        )
        from huggingface_hub import hf_hub_download

    _WEIGHTS_LOCAL_DIR.mkdir(parents=True, exist_ok=True)
    for repo_file in _WEIGHT_FILES:
        dest = _WEIGHTS_LOCAL_DIR / repo_file
        if dest.exists():
            print(f"  Already exists: {repo_file}")
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        print(f"  Downloading {Path(repo_file).name} ...", flush=True)
        hf_hub_download(
            repo_id=_HF_REPO_ID,
            filename=repo_file,
            local_dir=str(_WEIGHTS_LOCAL_DIR),
        )
    WEIGHTS_FLAG.touch()
    print("[LivePortrait] Weights download complete.")


def _ensure_hybrid_template() -> None:
    """Generate talking_with_movement.pkl if it doesn't already exist."""
    out = REPO_DIR / "assets" / "examples" / "driving" / "talking_with_movement.pkl"
    if out.exists():
        return
    drive_dir = REPO_DIR / "assets" / "examples" / "driving"
    if not (drive_dir / "talking.pkl").exists() or not (drive_dir / "d8.pkl").exists():
        return  # source files missing, skip
    import pickle
    import numpy as np
    with open(drive_dir / "talking.pkl", "rb") as f:
        talking = pickle.load(f)
    with open(drive_dir / "d8.pkl", "rb") as f:
        d8 = pickle.load(f)
    n_target = talking["n_frames"]
    d8_motion = d8["motion"]
    indices = np.linspace(0, len(d8_motion) - 1, n_target).astype(int)
    d8_exps = np.stack([d8_motion[i]["exp"] for i in indices])
    t_arr = np.linspace(0, 4 * np.pi, n_target)
    blink = np.where(np.abs(np.sin(t_arr * 0.7)) > 0.97, 0.05, 0.26).astype(np.float32)
    lip_signal = ((np.sin(t_arr) * 0.4 + 0.5) * np.abs(np.sin(t_arr * 2.3))) * 0.18
    hybrid = {
        "n_frames": n_target,
        "output_fps": talking["output_fps"],
        "motion": [
            {"scale": talking["motion"][i]["scale"],
             "R_d": talking["motion"][i]["R"],
             "exp": d8_exps[i],
             "t": talking["motion"][i]["t"]}
            for i in range(n_target)
        ],
        "c_d_eyes_lst": [np.array([[b, b]], dtype=np.float32) for b in blink],
        "c_d_lip_lst": [np.array([[float(lip_signal[i])]], dtype=np.float32) for i in range(n_target)],
    }
    with open(out, "wb") as f:
        pickle.dump(hybrid, f)
    print(f"[LivePortrait] Generated hybrid driving template: {out.name}")


def generate_animation(
    headshot_path: str,
    output_dir: str,
    template_video: str = "",
    fps: int = 25,
    duration_sec: float = 5.0,
    driving_multiplier: float = 1.0,
) -> dict:
    """
    Generate a talking animation from a static headshot using LivePortrait.

    Args:
        headshot_path:      Path to the source PNG/JPG headshot.
        output_dir:         Directory where the output .mp4 will be saved.
        template_video:     Path to a driving video or .pkl motion file.
                            Leave empty to use the built-in talking_with_movement.pkl
                            (10× more head/shoulder motion than stock d5.pkl).
        fps:                Frames per second for the output video.
        duration_sec:       Approximate duration (determined by the driving clip length).
        driving_multiplier: Amplify driving motion (1.0=normal, 1.3=more expressive).
                            Values above 1.5 may cause distortion.

    Returns:
        {
            "output_path": str,           # absolute path to output .mp4
            "duration":    float,
            "engine":      "liveportrait",
            "fps":         int,
            "metadata":    dict
        }

    Raises:
        FileNotFoundError: if headshot or template_video do not exist.
        RuntimeError:      if LivePortrait inference fails.
    """
    _setup()
    _download_weights()
    _ensure_hybrid_template()

    headshot_path = str(Path(headshot_path).resolve())
    output_dir = str(Path(output_dir).resolve())

    # Resolve driving template
    if template_video:
        driving = str(Path(template_video).resolve())
    elif Path(_DEFAULT_DRIVING).exists():
        driving = _DEFAULT_DRIVING
    else:
        driving = _FALLBACK_DRIVING  # d8.pkl if hybrid not yet built

    if not os.path.exists(headshot_path):
        raise FileNotFoundError(f"Headshot not found: {headshot_path}")
    if not os.path.exists(driving):
        raise FileNotFoundError(f"Driving template not found: {driving}")

    os.makedirs(output_dir, exist_ok=True)

    name = Path(headshot_path).stem
    lp_output_dir = str(Path(output_dir) / name)
    os.makedirs(lp_output_dir, exist_ok=True)

    print(f"[LivePortrait] Processing {name} ...")
    print(f"  source : {headshot_path}")
    print(f"  driving: {Path(driving).name}")

    cmd = [
        sys.executable, str(REPO_DIR / "inference.py"),
        "--source", headshot_path,
        "--driving", driving,
        "--output_dir", lp_output_dir,
        "--flag_force_cpu",
        "--no-flag_use_half_precision",
        "--driving_multiplier", str(driving_multiplier),
    ]

    if driving.endswith(".mp4"):
        cmd.append("--flag_crop_driving_video")

    # PYTHONUTF8=1 prevents rich's progress bar from crashing on Windows cp1252 terminals
    env = os.environ.copy()
    env["PYTHONUTF8"] = "1"
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(REPO_DIR), env=env)

    if result.returncode != 0:
        raise RuntimeError(
            f"LivePortrait inference failed for '{name}'.\n"
            f"STDERR:\n{result.stderr[-3000:]}\n"
            f"STDOUT:\n{result.stdout[-500:]}"
        )

    # Find the generated .mp4 and move it to the standardized output path
    candidates = sorted(
        glob.glob(os.path.join(lp_output_dir, "**", "*.mp4"), recursive=True),
        key=os.path.getmtime,
        reverse=True,
    )
    if not candidates:
        raise RuntimeError(f"No output .mp4 found in {lp_output_dir} after inference.")

    output_path = os.path.join(output_dir, f"{name}_talking.mp4")
    os.replace(candidates[0], output_path)

    print(f"[LivePortrait] Done -> {output_path}")
    return {
        "output_path": output_path,
        "duration": duration_sec,
        "engine": "liveportrait",
        "fps": fps,
        "metadata": {"driving": driving, "source": headshot_path},
    }


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate talking animation with LivePortrait (local CPU)"
    )
    parser.add_argument("--headshot", required=True, help="Path to source PNG headshot")
    parser.add_argument(
        "--template",
        default="",
        help="Driving video or .pkl (blank = talking_with_movement.pkl: head/shoulder + varied lips)",
    )
    parser.add_argument(
        "--output_dir",
        default=str(PROJECT_ROOT / "outputs" / "m1" / "liveportrait"),
    )
    parser.add_argument("--fps", type=int, default=25)
    parser.add_argument(
        "--driving_multiplier", type=float, default=1.0,
        help="Amplify motion (1.0=normal, 1.3=more expressive, >1.5 may distort)",
    )
    args = parser.parse_args()

    result = generate_animation(
        args.headshot, args.output_dir, args.template, args.fps,
        driving_multiplier=args.driving_multiplier,
    )
    print(f"\nResult: {result}")
